import {Injectable} from '@angular/core';
import {Kanji, kanjiFixture} from '@jp-aid/shared-interfaces';

@Injectable({
  providedIn: 'root'
})
export class MockData {
  getKanji = (): Kanji[] => [
    kanjiFixture('語', ['word', 'language'], ['ゴ'], ['かた(る)'], 14),
    kanjiFixture('日', ['day', 'sun'], ['ニチ', 'ジツ'], ['ひ', 'か'], 4),
    kanjiFixture('本', ['book', 'origin'], ['ホン'], ['もと'], 5),
    kanjiFixture('人', ['person'], ['ジン', 'ニン'], ['ひと'], 2),
    kanjiFixture('気', ['spirit', 'mind'], ['キ', 'ケ'], [], 6),
    kanjiFixture('水', ['water'], ['スイ'], ['みず'], 4),
    kanjiFixture('火', ['fire'], ['カ'], ['ひ'], 4),
    kanjiFixture('木', ['tree', 'wood'], ['モク', 'ボク'], ['き'], 4),
    kanjiFixture('金', ['gold', 'money'], ['キン', 'コン'], ['かね'], 8),
    kanjiFixture('土', ['earth', 'soil'], ['ド', 'ト'], ['つち'], 3),
    kanjiFixture('月', ['moon', 'month'], ['ゲツ', 'ガツ'], ['つき'], 4),
    kanjiFixture('山', ['mountain'], ['サン'], ['やま'], 3),
    kanjiFixture('川', ['river'], ['セン'], ['かわ'], 3),
    kanjiFixture('田', ['rice field'], ['デン'], ['た'], 5),
    kanjiFixture('天', ['heaven', 'sky'], ['テン'], ['あま'], 4),
    kanjiFixture('空', ['sky', 'empty'], ['クウ'], ['そら'], 8),
    kanjiFixture('雨', ['rain'], ['ウ'], ['あま'], 8),
    kanjiFixture('風', ['wind'], ['フウ', 'フ'], ['かぜ'], 9),
    kanjiFixture('花', ['flower'], ['カ'], ['はな'], 7),
    kanjiFixture('草', ['grass'], ['ソウ'], ['くさ'], 9),
    kanjiFixture('虫', ['insect'], ['チュウ'], ['むし'], 6),
    kanjiFixture('犬', ['dog'], ['ケン'], ['いぬ'], 4),
    kanjiFixture('猫', ['cat'], ['ビョウ'], ['ねこ'], 11),
    kanjiFixture('鳥', ['bird'], ['チョウ'], ['とり'], 11),
    kanjiFixture('魚', ['fish'], ['ギョ'], ['さかな'], 11),
    kanjiFixture('牛', ['cow'], ['ギュウ'], ['うし'], 4),
    kanjiFixture('馬', ['horse'], ['バ'], ['うま'], 10),
    kanjiFixture('羊', ['sheep'], ['ヨウ'], ['ひつじ'], 6),
    kanjiFixture('豚', ['pig'], ['トン'], ['ぶた'], 11),
    kanjiFixture('鹿', ['deer'], ['ロク'], ['しか'], 11),
    kanjiFixture('象', ['elephant'], ['ゾウ'], [], 14),
    kanjiFixture('虎', ['tiger'], ['コウ'], ['トラ'], 8),
    kanjiFixture('狼', ['wolf'], ['ロウ'], ['オオミツネ'], 10),
    kanjiFixture('熊', ['bear'], ['ユウ'], ['クマ'], 14),
    kanjiFixture('猿', ['monkey'], ['エン'], ['サル'], 13),
    kanjiFixture('龍', ['dragon'], ['リュウ'], ['ダン'], 16),
    kanjiFixture('亀', ['turtle'], ['キ'], ['カメ'], 11),
    kanjiFixture('蛇', ['snake'], ['ジャ'], ['ヘビ'], 11),
    kanjiFixture('蛙', ['frog'], ['ア'], ['カエル'], 12),
    kanjiFixture('鯨', ['whale'], ['ゲイ'], ['クジラ'], 19),
    kanjiFixture('鷹', ['hawk'], ['ユウ'], ['タカ'], 24),
    kanjiFixture('鴨', ['duck'], ['オウ'], ['カモ'], 16),
    kanjiFixture('鶴', ['crane'], ['カク'], ['ツル'], 21),
    kanjiFixture('鳩', ['pigeon'], ['キュウ'], ['ハト'], 13),
    kanjiFixture('鷲', ['eagle'], ['シュウ'], ['ワシ'], 23),
    kanjiFixture('鴉', ['crow'], ['ア'], ['カラス'], 15),
    kanjiFixture('鵬', ['mythical bird'], ['ホウ'], [], 19),
    kanjiFixture('鵠', ['swan'], ['コク'], ['ハクチョウ'], 19),
    kanjiFixture('鷗', ['seagull'], ['オウ'], ['カモメ'], 22),
    kanjiFixture('鷹', ['falcon'], ['ユウ'], ['タカ'], 24),
    kanjiFixture('鸚', ['parrot'], ['オウ'], [], 30),
    kanjiFixture('鸛', ['stork'], ['カン'], ['コウノトリ'], 24),
    kanjiFixture('鸞', ['phoenix'], ['ラン'], [], 30)
  ];
}
